language: python
python:
- "3.6"

# command to install dependencies
install:
- sudo docker pull centos
- sudo docker run -it centos
- dnf install epel-release
- yum install ansible
- yum install gluster-ansible-*

# command to run tests
script:
- sudo cp ~/gluster-ansible/sac.repo /etc/yum.repos.d/
- ansible --version
- sudo cp ~/gluster-ansible/playbooks/hc-ansible-deployment/node1_prep_inventory.yml /etc/ansible/roles/gluster.ansible/playbooks/hc-ansible-deployment/
- ansible-playbook -i node_prep_inventory.yml -i node1_replace_inventory.yml tasks/replace_node.yml --tags preparehost

