language: python
python:
- "3.6"

# command to install dependencies
install:

- dnf install epel-release
- yum install ansible
- yum install gluster-ansible-*

# command to run tests
script:
- cat >> /etc/yum.repos.d/sac.repo << EOF
[sac-gluster-ansible]
name=Copr repo for gluster-ansible owned by sac
baseurl=https://copr-be.cloud.fedoraproject.org/results/sac/gluster-ansible/epel-$releasever-x86_64/
type=rpm-md
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/sac/gluster-ansible/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
EOF
- ansible --version
- sudo cp ~/gluster-ansible/playbooks/hc-ansible-deployment/node1_prep_inventory.yml /etc/ansible/roles/gluster.ansible/playbooks/hc-ansible-deployment/
- ansible-playbook -i node_prep_inventory.yml -i node1_replace_inventory.yml tasks/replace_node.yml --tags preparehost

