language: python
python:
- "3.6"

sudo: required

services:
  - docker
# command to install dependencies
#

before_install:
- sudo docker pull centos

script:
- sudo docker pull centos
- sudo docker run -it --rm --detach centos > /tmp/container_id
- sudo docker exec "$(cat /tmp/container_id)" yum install -y epel-release
- sudo docker exec "$(cat /tmp/container_id)" yum install -y git 
- sudo docker exec "$(cat /tmp/container_id)" yum install -y  ansible
- sudo docker exec "$(cat /tmp/container_id)"  git clone  https://github.com/pkesavap/gluster-ansible.git
- sudo docker exec "$(cat /tmp/container_id)" cp /gluster-ansible/sac.repo /etc/yum.repos.d/
- sudo docker exec "$(cat /tmp/container_id)" yum install -y gluster-ansible-*
- sudo docker exec "$(cat /tmp/container_id)" cp /gluster-ansible/playbooks/hc-ansible-deployment/node1_prep_inventory.yml /etc/ansible/roles/gluster.ansible/playbooks/hc-ansible-deployment/
- ansible-playbook -i /etc/ansible/roles/gluster.ansible/playbooks/hc-ansible-deployment/node1_prep_inventory.yml -i /etc/ansible/roles/gluster.ansible/playbooks/hc-ansible-deployment/node_replace_inventory.yml /etc/ansible/roles/gluster.ansible/playbooks/hc-ansible-deployment/tasks/replace_node.yml --tags preparehost
